###  Random Forest
 
Assignment


About the data: 
Let’s consider a Company dataset with around 10 variables and 400 records. 
The attributes are as follows: 
 Sales -- Unit sales (in thousands) at each location
 Competitor Price -- Price charged by competitor at each location
 Income -- Community income level (in thousands of dollars)
 Advertising -- Local advertising budget for company at each location (in thousands of dollars)
 Population -- Population size in region (in thousands)
 Price -- Price company charges for car seats at each site
 Shelf Location at stores -- A factor with levels Bad, Good and Medium indicating the quality of the shelving location for the car seats at each site
 Age -- Average age of the local population
 Education -- Education level at each location
 Urban -- A factor with levels No and Yes to indicate whether the store is in an urban or rural location
 US -- A factor with levels No and Yes to indicate whether the store is in the US or not
The company dataset looks like this: 
 
Problem Statement:
A cloth manufacturing company is interested to know about the segment or attributes causes high sale. 
Approach - A Random Forest can be built with target variable Sales (we will first convert it in categorical variable) & all other variable will be independent in the analysis.  


In [1]:
import pandas as pd 
import numpy as np 
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
pd.options.mode.chained_assignment = None   # its used for some errors are ignoring

In [2]:
data = pd.read_csv('Company_Data.csv')
data.head()

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0   9.50        138      73           11         276    120       Bad   42   
1  11.22        111      48           16         260     83      Good   65   
2  10.06        113      35           10         269     80    Medium   59   
3   7.40        117     100            4         466     97    Medium   55   
4   4.15        141      64            3         340    128       Bad   38   

   Education Urban   US  
0         17   Yes  Yes  
1         10   Yes  Yes  
2         12   Yes  Yes  
3         14   Yes  Yes  
4         13   Yes   No

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Sales        400 non-null    float64
 1   CompPrice    400 non-null    int64  
 2   Income       400 non-null    int64  
 3   Advertising  400 non-null    int64  
 4   Population   400 non-null    int64  
 5   Price        400 non-null    int64  
 6   ShelveLoc    400 non-null    object 
 7   Age          400 non-null    int64  
 8   Education    400 non-null    int64  
 9   Urban        400 non-null    object 
 10  US           400 non-null    object 
dtypes: float64(1), int64(7), object(3)
memory usage: 34.5+ KB


In [4]:
data['high']=data.Sales.map(lambda x: 1 if x>8 else 0)

###  Converting the data type

In [5]:
data['ShelveLoc'] = data['ShelveLoc'].astype ('category')
data['Urban'] = data['Urban'].astype('category')
data['US'] = data['US'].astype('category')

In [6]:
#### data convert category to integer

In [7]:
data['ShelveLoc']=data['ShelveLoc'].cat.codes
data['Urban'] = data['Urban'].cat.codes
data['US'] = data['US'].cat.codes

In [8]:
data.head()

Sales  CompPrice  Income  Advertising  Population  Price  ShelveLoc  Age  \
0   9.50        138      73           11         276    120          0   42   
1  11.22        111      48           16         260     83          1   65   
2  10.06        113      35           10         269     80          2   59   
3   7.40        117     100            4         466     97          2   55   
4   4.15        141      64            3         340    128          0   38   

   Education  Urban  US  high  
0         17      1   1     1  
1         10      1   1     1  
2         12      1   1     1  
3         14      1   1     0  
4         13      1   0     0

In [9]:
data.dtypes

Sales          float64
CompPrice        int64
Income           int64
Advertising      int64
Population       int64
Price            int64
ShelveLoc         int8
Age              int64
Education        int64
Urban             int8
US                int8
high             int64
dtype: object

In [10]:
array = data.values

In [11]:
x = array[:,1:11]
y = array[:,11:]

In [12]:
print(x)

[[138.  73.  11. ...  17.   1.   1.]
 [111.  48.  16. ...  10.   1.   1.]
 [113.  35.  10. ...  12.   1.   1.]
 ...
 [162.  26.  12. ...  18.   1.   1.]
 [100.  79.   7. ...  12.   1.   1.]
 [134.  37.   0. ...  16.   1.   1.]]


In [13]:
print(y)

[[1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.

In [14]:
data.describe()

Sales   CompPrice      Income  Advertising  Population  \
count  400.000000  400.000000  400.000000   400.000000  400.000000   
mean     7.496325  124.975000   68.657500     6.635000  264.840000   
std      2.824115   15.334512   27.986037     6.650364  147.376436   
min      0.000000   77.000000   21.000000     0.000000   10.000000   
25%      5.390000  115.000000   42.750000     0.000000  139.000000   
50%      7.490000  125.000000   69.000000     5.000000  272.000000   
75%      9.320000  135.000000   91.000000    12.000000  398.500000   
max     16.270000  175.000000  120.000000    29.000000  509.000000   

            Price   ShelveLoc         Age   Education       Urban          US  \
count  400.000000  400.000000  400.000000  400.000000  400.000000  400.000000   
mean   115.795000    1.307500   53.322500   13.900000    0.705000    0.645000   
std     23.676664    0.833475   16.200297    2.620528    0.456614    0.479113   
min     24.000000    0.000000   25.000000   10.000000    0.000000    0.000000   
25%    100.000000    1.000000   39.750000   12.000000    0.000000    0.000000   
50%    117.000000    2.000000   54.500000   14.000000    1.000000    1.000000   
75%    131.000000    2.000000   66.000000   16.000000    1.000000    1.000000   
max    191.000000    2.000000   80.000000   18.000000    1.000000    1.000000   

             high  
count  400.000000  
mean     0.410000  
std      0.492449  
min      0.000000  
25%      0.000000  
50%      0.000000  
75%      1.000000  
max      1.000000

In [15]:
num_trees = 100
max_feature = 4

In [16]:
kfold = KFold(n_splits = 10 , random_state = 10,shuffle=True)

In [17]:
model = RandomForestClassifier(n_estimators = num_trees, max_features = max_feature)

In [18]:
results = cross_val_score(model,x,y,cv = kfold)

C:\Users\Solan\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:593: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Solan\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:593: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Solan\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:593: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Solan\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:593: DataConversionWarning: A column-vector y wa

In [19]:
print(results.mean())

0.82


#  Q 
 ## Use Random Forest to prepare a model on fraud data 
treating those who have taxable_income <= 30000 as "Risky" and others are "Good"


In [95]:
fraud = pd.read_csv('Fraud_check.csv')
fraud.head()

Undergrad Marital.Status  Taxable.Income  City.Population  Work.Experience  \
0        NO         Single           68833            50047               10   
1       YES       Divorced           33700           134075               18   
2        NO        Married           36925           160205               30   
3       YES         Single           50190           193264               15   
4        NO        Married           81002            27533               28   

  Urban  
0   YES  
1   YES  
2   YES  
3   YES  
4    NO

In [96]:
fraud1 = fraud.rename({'Marital.Status':'Married','Taxable.Income':'Tax','City.Population':'Population','Work.Experience':'Work'},axis=1)

In [97]:
fraud1.dtypes

Undergrad     object
Married       object
Tax            int64
Population     int64
Work           int64
Urban         object
dtype: object

In [98]:
fraud1['tax'] = fraud1.Tax.map(lambda x:1 if x<=30000 else 0)

In [99]:
fraud1.head()

Undergrad   Married    Tax  Population  Work Urban  tax
0        NO    Single  68833       50047    10   YES    0
1       YES  Divorced  33700      134075    18   YES    0
2        NO   Married  36925      160205    30   YES    0
3       YES    Single  50190      193264    15   YES    0
4        NO   Married  81002       27533    28    NO    0

###  converting data types

In [100]:
fraud1['Married'] = fraud1['Married'].astype('category')
fraud1['Undergrad'] = fraud1['Undergrad'].astype('category')
fraud1['Urban'] = fraud1['Urban'].astype('category')

In [101]:
# convert datatype category to numeric
fraud1['Married'] = fraud1['Married'].cat.codes
fraud1['Undergrad'] = fraud1['Undergrad'].cat.codes
fraud1['Urban'] = fraud1['Urban'].cat.codes

In [102]:
fraud1.dtypes

Undergrad      int8
Married        int8
Tax           int64
Population    int64
Work          int64
Urban          int8
tax           int64
dtype: object

In [103]:
fraud1.drop('Tax',axis=1)

Undergrad  Married  Population  Work  Urban  tax
0            0        2       50047    10      1    0
1            1        0      134075    18      1    0
2            0        1      160205    30      1    0
3            1        2      193264    15      1    0
4            0        1       27533    28      0    0
..         ...      ...         ...   ...    ...  ...
595          1        0       39492     7      1    0
596          1        0       55369     2      1    0
597          0        0      154058     0      1    0
598          1        1      180083    17      0    0
599          0        0      158137    16      0    0

[600 rows x 6 columns]

In [104]:
data2 = fraud1.values

In [105]:
X = data2[:,0:5]
Y = data2[:,5:]

###  Random forest

In [106]:
num_trees = 100

In [107]:
max_featue= 3

In [108]:
kfold = KFold(n_splits = 10 , random_state =7, shuffle=True)

In [109]:
model = RandomForestClassifier(n_estimators = num_trees,n_jobs = max_featue,)

In [110]:
results = cross_val_score(model, X, Y, cv = kfold)

In [111]:
print(results.mean())

0.5566666666666666
